SIGCTM/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),




    path('', views.home_view, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('configuracao/', views.configuracao_view, name='configuracao'),
    path('usuarios/', include('usuario.urls')), 
    path('notificacao/', include('notificacao.urls')),
    path('atividade/', include('atividade.urls')),
    path('oficios/', include('oficio.urls')),
    path('assistido/', include('assistido.urls')),
    path('atendimento/', include('atendimento.urls')),
    path('estatisticas/', include('estatistica.urls')),
    path('backup/', include('backup.urls')),
    path('protocolos/', include('protocolo.urls')),
    
    
    
]

assistido/urls.py
from django.urls import path
from . import views
from . import archive_actions

app_name = 'assistido'

urlpatterns = [
    path('deletar/<int:id_assist>/', views.deletar_assistido, name='deletar'),
    path('arquivar-morto/<int:id_assist>/', archive_actions.arquivar_morto_assistido, name='arquivar_morto'),
    path('desarquivar-morto/<int:id_assist>/', archive_actions.desarquivar_morto_assistido, name='desarquivar_morto'),
    path('', views.assistido_view, name='assistidos'),
    path('assistido/', views.assistido_view, name='assistido'),
    path('editar/<int:id_assist>/', views.editar_assistido, name='editar'),
    path('detalhe/<int:id_assist>/', views.detalhe_assistido, name='detalhe'),
    path('add-irmao/<int:id_assist>/', views.add_irmao, name='add_irmao'),
    path('remover-irmao/<int:id_assist>/<int:id_irmao>/', views.remover_irmao, name='remover_irmao'),
    path('add-local/<int:id_assist>/', views.add_local, name='add_local'),
    path('cadastrar/', views.cadastrar_assistido, name='cadastrar'),
    path('arquivar/<int:id_assist>/', archive_actions.arquivar_assistido, name='arquivar'),
    path('desarquivar/<int:id_assist>/', archive_actions.desarquivar_assistido, name='desarquivar'),
]

atividade/urls.py
from django.urls import path
from . import views

app_name = 'atividade'

urlpatterns = [
    path('', views.log, name='index'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
]

oficio/urls.py
from django.urls import path
from . import views

app_name = 'oficio'

urlpatterns = [
    path('', views.oficios, name='oficios'),
]

protocolo/urls.py
from django.urls import path
from . import views

app_name = 'protocolo'

urlpatterns = [
    path('', views.protocolos, name='protocolos'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
def dashboard_view(request):
    return render(request, 'core/dashboard.html', {
        'page_title': 'Início',
        'pagina_atual': 'dashboard'
    })
from django.shortcuts import render

from django.shortcuts import redirect

def home_view(request):
    return redirect('usuario:login')

def configuracao_view(request):
    return render(request, 'core/configuracao.html', {
        'page_title': 'Configurações',
        'pagina_atual': 'configuracao'
    })
# Create your views here.

core/templates/partials/bottom-code.html
{% load static %}
    {% include 'partials/rodape.html' %}

    <script src="{% static 'js/main-bottom.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
        crossorigin="anonymous"></script>
</body>

</html>

core/templates/partials/favicon.html
{% load static %}
<link rel="icon" href="{% static 'img/logo/favicon.light/favicon.light.svg' %}" type="image/png">

core/templates/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% include 'partials/favicon.html' %}
    <title>
        {% if page_title == "Início" %}
            Início | Conselho Tutelar
        {% elif page_title == "Assistido" %}
            Assistido | Conselho Tutelar
        {% elif page_title == "Assistidos" %}
            Assistidos | Conselho Tutelar
        {% elif page_title == "Atendimento" %}
            Atendimento | Conselho Tutelar
        {% elif page_title == "Atendimentos" %}
            Atendimentos | Conselho Tutelar
        {% elif page_title == "Notificação" %}
            Notificação | Conselho Tutelar
        {% elif page_title == "Ofício" %}
            Ofício | Conselho Tutelar
        {% elif page_title == "Protocolo" %}
            Protocolo | Conselho Tutelar
        {% elif page_title == "Atividade" %}
            Atividade | Conselho Tutelar
        {% elif page_title == "Backup" %}
            Backup | Conselho Tutelar
        {% elif page_title == "Configurações" %}
            Configurações | Conselho Tutelar
        {% else %}
            Conselho Tutelar
        {% endif %}
    </title>
</head>

core/templates/partials/header.html
{% load static %}
<header class=" bg-body-tertiary">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <a href="" class="navbar-brand d-lg-block d-none">
                    <img src="{% static 'img/logo/logo.light.svg' %}" alt="" width="40px">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a href="" class="navbar-brand d-lg-none d-block">
                    <img src="{% static 'img/logo/logo.light.svg' %}" alt="" width="40px">
                </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    {% include 'partials/navtop.html' %}
                </div>

                <div class="d-flex align-items-center gap-3 ">
                    <a class="d-none d-lg-flex" id="tema-interruptor" onclick="intTema()">
                        <i class="bi bi-circle-half"></i>
                    </a>
                    <div class="dropdown text-end">
                        <a href="" class="d-block link-body-emphasis text-decoration-none dropdown-toggle show"
                            aria-expanded="true" data-bs-toggle="dropdown">
                            <img src="{% static 'img/pfp/unknow.jpg' %}" alt="" width="35px" class="rounded-circle">
                        </a>
                        <ul class="dropdown-menu text-small"
                            style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(-100px, 40px, 0px);"
                            data-popper-placement="bottom-start">
                            <li><a class="dropdown-item" href="{% url 'configuracao' %}"><i class="bi bi-gear pe-2"></i>Configurações</a></li>
                            <li><a class="dropdown-item" href="{% url 'backup' %}"><i class="bi bi-cloud-arrow-up pe-2"></i>Backup</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'atividade:index' %}"><i class="bi bi-clock-history pe-2"></i>Atividade</a>
                            </li>
                            <li><a class="dropdown-item" href="#"><i class="bi bi-bar-chart pe-2"></i>Estatísticas</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Sair</a></li>
                        </ul>

                        </ul>
                    </div>
                </div>

            </nav>
        </div>
        <div class="container d-flex align-items-center justify-content-between">
            <h6 class="text-muted">> 
                {% if page_title == "Início" %}
                    Início
                {% elif page_title == "Assistido" %}
                    Assistido
                {% elif page_title == "Assistidos" %}
                    Assistidos
                {% elif page_title == "Atendimento" %}
                    Atendimento
                {% elif page_title == "Atendimentos" %}
                    Atendimentos
                {% elif page_title == "Notificação" %}
                    Notificação
                {% elif page_title == "Ofício" %}
                    Ofício
                {% elif page_title == "Protocolo" %}
                    Protocolo
                {% elif page_title == "Atividade" %}
                    Atividade
                {% elif page_title == "Backup" %}
                    Backup
                {% elif page_title == "Configurações" %}
                    Configurações
                {% else %}
                    Conselho Tutelar
                {% endif %}
            </h6>
            <ul class="nav gap-4 flex-nowrap overflow-auto small">
                <li class="nav-item"><a href="#dvoffcanvas" class="link-secondary" data-bs-toggle="offcanvas"
                        role="button" aria-controls="dvoffcanvas">Direito violado</a></li>
                <div class="vr"></div>
                <li class="nav-item"><a href="#rioffcanvas" class="link-secondary" data-bs-toggle="offcanvas"
                        role="button" aria-controls="rioffcanvas">Regimento interno</a></li>
                <div class="vr"></div>
                <li class="nav-item"><a href="{% static 'pdf/eca_1ed.pdf' %}" target="_blank" class="link-secondary">ECA</a></li>
            </ul>
            {% include 'partials/offcanvas-ri-dv.html' %}
        </div>
    </header>

core/templates/partials/navtop.html
<ul class="navbar-nav nav nav-underline">
    <li class="nav-item">
        <a class="nav-link {% if pagina_atual == 'dashboard' %}active{% endif %}" aria-current="page" href="{% url 'dashboard' %}">
            <i class="bi bi-house-fill pe-1"></i>
            Início
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if pagina_atual == 'assistidos' %}active{% endif %}" href="{% url 'assistido:assistidos' %}">
            <i class="bi bi-person-fill pe-1"></i>
            Assistido
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if pagina_atual == 'atendimento' %}active{% endif %}" href="{% url 'atendimento:atendimento' %}">
            <i class="bi bi-headset pe-1"></i>
            Atendimento
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if pagina_atual == 'notificacao' %}active{% endif %}" href="{% url 'notificacao:notificacao' %}">
            <i class="bi bi-bell-fill pe-1"></i>
            Notificação
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if pagina_atual == 'oficio' %}active{% endif %}" href="{% url 'oficio:oficios' %}">
            <i class="bi bi-briefcase-fill pe-1"></i>
            Ofício
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link {% if pagina_atual == 'protocolo' %}active{% endif %}" href="{% url 'protocolo:protocolos' %}">
            <i class="bi bi-file-earmark-text pe-1"></i>
            Protocolo
        </a>
    </li>
</ul>

core/templates/partials/offcanvas-ri-dv.html
<!-- Offcanvas do Regimento Interno-->
    <div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="rioffcanvas"
        aria-labelledby="offcanvasRioLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRioLabel">Regimento Interno</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <p>Texto do Regimento Interno</p>
        </div>
    </div><!-- Offcanvas do Regimento Interno-->
    <!-- Offcanvas do Direito Violado-->
    <div class="offcanvas offcanvas-end" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="dvoffcanvas"
        aria-labelledby="offcanvasDvLabel">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasDvLabel">Direito Violado</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <p>Texto do Direito Violado</p>
        </div>
    </div><!-- Offcanvas do Direito Violado-->

core/templates/partials/rodape.html
    <footer class="--bs-secondary-color bg-body-tertiary text-body-secondary">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-12 col-lg-3">
                    <h4 class="border-bottom border-5 d-inline-block">Responsáveis pela plataforma</h4>
                    <h5>Desenvolvedores</h5>
                    <ul class="list-unstyled">
                        <li>Ana Carolina Carnelos Masquetti</li>
                        <li>Vitor Mollo Cunha</li>
                    </ul>

                    <h5>Orientador</h5>
                    <ul class="list-unstyled">
                        <li>Renato Oliveira Violin</li>
                    </ul>

                    <h5>Contato para suporte</h5>
                    <ul class="list-unstyled">
                        <li>Email: <a href="mailto:conselhotutelar@mococa.sp.gov.br">conselhotutelar@mococa.sp.gov.br</a></li>
                    </ul>
                </div>
                <div class="col-12 col-lg-3">
                    <h4 class="border-bottom border-5 d-inline-block">Sobre a plataforma</h4>
                    <p>Este projeto faz parte do trabalho de conclusão de curso <strong>de Gestão da Tecnologia de Informação</strong> na FATEC Mococa.</p>
                    <a href="">Trabalho escrito</a>
                </div>
                <div class="col-12 col-lg-6">
                    <h4 class="border-bottom border-5 d-inline-block">Sobre o Conselho Tutelar de Mococa</h4>
                    <div class="row">
                        <div class="col-6">
                            <h5>Contato</h5>
                            <ul class="list-unstyled">
                                <li>Email: <a href="mailto:conselho@mococa.sp.gov.br">conselho@mococa.sp.gov.br</a></li>
                                <li>Telefone: <a href="tel:+551930941571">+55 19 3094-1571</a></li>
                                <li>Telefone: <a href="tel:+551936561483">+55 19 3656-1483</a></li>
                                <li>Telefone: <a href="tel:+5519992028709">+55 19 99202-8709</a></li>
                                <li>Telefone: <a href="tel:+5519997099614">+55 19 99709-9614</a></li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h5>Endereço</h5>
                            <ul class="list-unstyled">
                                <li>Rua Capitão Miguel Ferreira, 533 - Vila Mariana</li>
                                <li>Mococa - SP</li>
                                <li>CEP: 12345-678</li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h5>Informações Adicionais</h5>
                            <ul class="list-unstyled">
                                <li>Site: <a href="https://www.mococa.sp.gov.br">www.mococa.sp.gov.br</a></li>
                                <li>Facebook: <a href="https://www.facebook.com/conselho.mococa">facebook.com/conselho.mococa</a></li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <h5>Mandato atual</h5>
                            <ul class="list-unstyled">
                                <li>Conselheira um</li>
                                <li>Conselheira dois</li>
                                <li>Conselheira três</li>
                                <li>Conselheira quatro</li>
                                <li>Conselheira cinco</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

core/templates/partials/top-code.html
{% include 'partials/head.html' %}
<body>
    {% include 'partials/header.html' %}
    {% include 'partials/offcanvas-ri-dv.html' %}


    